FROM centos/python-27-centos7
#ENV centos=centos/python-35-centos
RUN sudo yum install httpd httpd-tools -y && echo "My Website" >> /var/www/html/index.html
#RUN yum install vim -y
RUN cd 
RUN sudo curl -O https://bootstrap.pypa.io/get-pip.py && python get-pip.py 
RUN sudo curl https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py -O && python ./awslogs-agent-setup.py --region us-east-1
RUN sudo echo -e "[/var/log/apache2/access.log]\ state_file = /var/log/httpd/access.log\ log_group_name = log-docker " > /root/awslogs.conf
RUN sudo mkdir -p /root/.aws && touch /root/.aws/credentials
RUN sudo echo -e "[default]\ aws_access_key_id = AKIATMAG2QJAK4YKVNMW\ aws_secret_access_key = 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 " /root/.aws/credentials
RUN sudo python ./awslogs-agent-setup.py --region us-east-1 --non-interactive --configfile=/root/awslogs.conf
RUN service awslogs start
CMD [ "/usr/sbin/httpd","-D","FOREGROUND" ]